#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

easy_admin:
    site_name: 'Portfolio'

    entities:
      Skill:
          class: App\Entity\Skill
          title: 'les compétences'
          list:
            fields:
               - {property: 'description', label: 'skill.description'}
               - {property: 'pourcentage', label: 'skill.pourcentage'}
      Project:
          class: App\Entity\Project
          list:
            fields:
               - {property: 'title', label: 'project.title'}
               - {property: 'description', label: 'project.description'}
               - {property: 'adressURL', label: 'project.adressURL'}
               - {property: 'createdAt', label: 'project.createdAt'}
               - {property: 'image', type: 'image', base_path: '%app.path.project_images%' }
          form:
            fields: ['title', 'description', {property: imageFile, type: 'vich_image'},{property: 'createdAt', type_options: { widget: 'single_text'}}]
      
      Contact:
          class: App\Entity\Contact
          disabled_actions: ['edit', 'new']

